Import('env', 'plugins')

plugins += env.SharedLibrary('perspective', ['perspective.cpp'])
plugins += env.SharedLibrary('perspective_rdist', ['perspective_rdist.cpp'])
plugins += env.SharedLibrary('orthographic', ['orthographic.cpp'])
plugins += env.SharedLibrary('spherical', ['spherical.cpp'])
plugins += env.SharedLibrary('pushbroom', ['pushbroom.cpp'])
plugins += env.SharedLibrary('hemispherical_fisheye', ['hemispherical_fisheye.cpp'])

Export('plugins')
