Import('env', 'plugins')

plugins += env.SharedLibrary('homogeneous', ['homogeneous.cpp'])
plugins += env.SharedLibrary('heterogeneous', ['heterogeneous.cpp'])
plugins += env.SharedLibrary('planeparallel', ['planeparallel.cpp'])
plugins += env.SharedLibrary('vegmedium', ['vegmedium.cpp'])
Export('plugins')
