""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"D:\Anaconda\envs\mitsuba3_env_py3_10\python.exe"
MI_DEFAULT_VARIANT = ''
MI_VARIANTS = ['scalar_rgb', 'scalar_spectral', 'cuda_ad_spectral', 'cuda_spectral']
DRJIT_VERSION_REQUIREMENT = '0.4.6'
CXX_COMPILER = 'MSVC 19.41.34120.0'
