Import('env', 'plugins')

# Basic library of smooth and rough materials
plugins += env.SharedLibrary('diffuse', ['diffuse.cpp'])

# Materials that act as modifiers
plugins += env.SharedLibrary('twosided', ['twosided.cpp'])
plugins += env.SharedLibrary('mixturebsdf', ['mixturebsdf.cpp'])

# Other materials
plugins += env.SharedLibrary('difftrans', ['difftrans.cpp'])
plugins += env.SharedLibrary('null', ['null.cpp'])

plugins += env.SharedLibrary('soilspect', ['soilspect.cpp'])

Export('plugins')
