Import('mainEnv', 'hasCollada', 'stubs', 'winstubs')


converter_objects = []

import platform

colladaEnv = mainEnv.Clone()
converter_objects += [
	# colladaEnv.StaticObject('collada.cpp'),
	colladaEnv.StaticObject('obj.cpp'),
	colladaEnv.StaticObject('converter.cpp')
]
colladaEnv.Program('mtsimport', stubs + winstubs + ['mtsimport.cpp'] 
	+ converter_objects)

Return('converter_objects')
