Import('env', 'plugins')

plugins += env.SharedLibrary('isotropic', ['isotropic.cpp'])
plugins += env.SharedLibrary('hg', ['hg.cpp'])
plugins += env.SharedLibrary('rayleigh', ['rayleigh.cpp'])
plugins += env.SharedLibrary('vegphase', ['vegphase/vegphase.cpp'])
plugins += env.SharedLibrary('mixturephase', ['mixturephase.cpp'])
plugins += env.SharedLibrary('vegFluorphase', ['vegFluorphase/vegFluorphase.cpp'])

Export('plugins')
