Import('env', 'plugins')

plugins += env.SharedLibrary('isotropic', ['isotropic.cpp'])
plugins += env.SharedLibrary('hg', ['hg.cpp'])
plugins += env.SharedLibrary('rayleigh', ['rayleigh.cpp'])
plugins += env.SharedLibrary('mixturephase', ['mixturephase.cpp'])

Export('plugins')
